data_loader_config:
  batch_size: 32
  data_containers_config:
  - WL_TS
  - WL_SU
  - WL_SD
  - WL_SI
  - WL_SS
  num_workers: 4
  shuffle: true
  windows_count: {}
dataset_config:
  balance_dataset: true
  input_noise:
    apply: true
    params_per_input:
      MASS_FLOW_T1:
        percent_accuracy_in_span: 0.5
        span:
        - 0
        - 187.87
        transmitter_smoothing_scaling_factor: 0.0625
      PRESSURE_T1:
        percent_precision_in_span: 0.075
        span:
        - -99973.981
        - 1378951.458
        transmitter_smoothing_scaling_factor: 0.0625
  leak_location_levels:
  - 50.0
  - 250.0
  - 500.0
  - 750.0
  - 1000.0
  - 1150.0
  - 1300.0
  leak_size_levels:
  - 0.25
  - 0.5
  - 0.75
  - 1.0
  - 1.25
  normalize: true
  path: /home/intelcon/idetectfugas/data/tdp/SUPE/L1L/DIESEL
  path_of_sim_cases_to_consider: ''
  train_split: 0.8
  used_data_containers:
  - /home/intelcon/idetectfugas/data/tdp/SUPE/L1L/DIESEL/SU_L1L_D_WL_SD_V2
  - /home/intelcon/idetectfugas/data/tdp/SUPE/L1L/DIESEL/SU_L1L_D_WL_TS1_V2
  - /home/intelcon/idetectfugas/data/tdp/SUPE/L1L/DIESEL/SU_L1L_D_WL_SI_V2
  - /home/intelcon/idetectfugas/data/tdp/SUPE/L1L/DIESEL/SU_L1L_D_WL_SU_V2
  - /home/intelcon/idetectfugas/data/tdp/SUPE/L1L/DIESEL/SU_L1L_D_WL_TS2_V2
  - /home/intelcon/idetectfugas/data/tdp/SUPE/L1L/DIESEL/SU_L1L_D_WL_TS3_V2
  - /home/intelcon/idetectfugas/data/tdp/SUPE/L1L/DIESEL/SU_L1L_D_WL_SS_V2
metadata:
  additional_information:
    attachments: Links to additional files
    notes: Any additional notes
    references: Links to documents, papers
  model_architecture: ''
  model_identification:
    author: Idetect Fugas
    creation_date: '2025-01-20T19:01:30Z'
    model_name: example_model
    version: 1.0.0
  model_performance_metrics: {}
  model_training_details:
    data_source: 'from google drive (TODO: WHEN BETTER DATASET ORGANIZATION)'
    hyperparameters:
      batch_size: 32
    training_dataset: 'Name or ID of the dataset (TODO: WHEN BETTER DATASET ORGANIZATION)'
    training_duration: ''
    training_environment:
      cpu_count: 32
      cpu_percent: 0.0
      disk_free: 12988280832
      disk_total: 116012584960
      disk_used: 97083912192
      gpu_info: No GPU detected
      machine: x86_64
      network_received: 1894945296
      network_sent: 302645923
      platform: Linux-6.1.0-28-amd64-x86_64-with-glibc2.36
      processor: ''
      ram_available: 15546667008
      ram_total: 16466882560
      uname:
        machine: x86_64
        node: intelcon
        processor: ''
        release: 6.1.0-28-amd64
        system: Linux
        version: '#1 SMP PREEMPT_DYNAMIC Debian 6.1.119-1 (2024-11-22)'
      version: '#1 SMP PREEMPT_DYNAMIC Debian 6.1.119-1 (2024-11-22)'
    training_method: Transformer architecture. More info to be filled soon
  model_usage_and_deployment:
    deployment_status: Deployed/Not Deployed
    endpoint_information: API endpoint if applicable
    use_case_description: Description of the model's intended use
  regulatory_and_compliance_information:
    audit_trail: Records of modifications or reviews
    data_privacy: GDPR compliant/Not compliant
    ethical_considerations: Notes on biases, ethical considerations
model_config:
  adam_b1: 0.9
  adam_b2: 0.98
  adam_eps: 9.0e-09
  d_model: 128
  dim_feedforward: 2048
  gt_indexes:
    leak_flow_idx: 2
    leak_location_idx: 1
    leak_size_idx: 0
  inputs:
  - MASS_FLOW_T1
  - PRESSURE_T1
  kernel_size_time2vec: 10
  model_type:
    module: DIAGNOSIS
    operational_mode: ALL_MODES
    optimization_task: CLASSIFICATION
  n_head: 8
  name: CLASSIFICATION_DIAGNOSIS_ALL_MODES_L1L
  num_encoder_layers: 2
  num_hidden_neurons: 256
  num_linear_layers: 3
  outputs:
  - class_names:
    - '0.25'
    - '0.5'
    - '0.75'
    - '1.0'
    - '1.25'
    classification_threshold: null
    custom_name: leak_size
    gt_index: 0
    importance: 0.1
    loss_params: {}
    optimized_via.value: CLASSIFICATION
  - class_names:
    - '50.0'
    - '250.0'
    - '500.0'
    - '750.0'
    - '1000.0'
    - '1150.0'
    - '1300.0'
    classification_threshold: null
    custom_name: leak_location
    gt_index: 1
    importance: 0.8
    loss_params: {}
    optimized_via.value: CLASSIFICATION
  - custom_name: leak_flow
    gt_index: 2
    importance: 0.1
    loss_params: {}
    optimized_via.value: REGRESSION
  positional_encoding: true
  saving_path: /home/intelcon/idetectfugas/data/saved_models/SUPE/PFM/DIAGNOSIS/ALL_MODES/2025-01-20_14-01-31_CLASSIFICATION_DIAGNOSIS_ALL_MODES_L1L
  window_size: 40
training_config:
  dropout: 0.0
  early_stopping:
    apply: true
    params:
      min_delta: 0.0001
      patience: 5
  epochs: 50
  lr_after_warmup: 0.0015
  lr_decay: 0.999994
  lr_scheduler_last_epoch: -1
  save_checkpoint_every: 5
  warmup_steps: 5000
